name: run-tests

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build docker image
        run: |
          echo "Building image"
          docker build -t my-app:latest .
  unit-tests:
      name: Run unit tests
      runs-on: ubuntu-latest
      outputs:
        result: ${{ steps.tests.outputs.unit-test-result }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - id: tests
          name: Run tests
          # uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
          run: |
            echo "Unit Tests are running..."
            npm ci
            npm test

  collate-test-results:
      name: Check results
      runs-on: ubuntu-latest
      needs: [unit-tests, build-image]

      steps:
        - name: Print Results
          run: echo "The result of the Unit Tests was ${{ needs.unit-tests.outputs.result }}"